[Unit]
Wants=euro-office.container

[Container]
Environment=OC_ADD_RUN_SERVICES=collaboration
Environment=COLLABORATION_APP_NAME=Euro-Office
Environment=COLLABORATION_APP_PRODUCT=OnlyOffice
Environment=COLLABORATION_APP_INSECURE=false
Environment=COLLABORATION_CS3API_DATAGATEWAY_INSECURE=false
Environment=COLLABORATION_APP_PROOF_DISABLE=true

Volume=./config/euro-office/app-registry.yaml:/etc/opencloud/app-registry.yaml:z
